### ISSUE TITLE
App crashes in NSJSONReader parseData:options:error inside OIDIDToken.m

### ISSUE THREAD

**Issue by awBSH** [openid/AppAuth-iOS#737] opened 2022-12-02 10:08 UTC
**Describe the bug**
Since October 24th (release day of iOS16.1), we are observing an increase in crashes.

It crashes in various places of our App but we could identify certain patterns:
> * it started on October 24th
> * it crashes only in iOS16.1 and later
> * it crashes in all our versions of the App (seems to not tie to a recent change of us)
> * second biggest group of crashes seems to come from JSONDecoder (but also NSJSONReader) (which we use in our code and is used by 3rd-party libraries like Lottie, App-Auth...)

One crash comes specifically from `OIDIDToken.m:118`, this is where the JWT-token is being parsed.

```
Thread 0 Crashed:
0   libobjc.A.dylib                      0x000000019c7c5c08 objc_msgSend + 8
1   CoreFoundation                       0x00000001a34b5ea4 ____NSDictionaryI_new_block_invoke + 180
2   CoreFoundation                       0x00000001a352a1b8 __NSDictionaryI_new + 476
3   Foundation                           0x000000019d91f2dc newJSONObject + 1396
4   Foundation                           0x000000019d91f9f8 newJSONValue + 492
5   Foundation                           0x000000019d8f69f8 -[_NSJSONReader parseData:options:error:] + 1092
6   OUR_APP                              0x0000000105296274 +[OIDIDToken parseJWTSection:] (OIDIDToken.m:118)
```

With the given information, we assume something changed in iOS16.1 with the `NSJSONReader`.

### Has anyone made similar observations with such crashes from iOS16.1?

**To Reproduce**
We can't reproduce the crash, but we only see the (anonymized) crash-reports.

**Expected behavior**
no crashes

**Screenshots**
N/A

**Environment**
- Device: all iPhones + iPads
- OS: iOS16.1 and later

**Additional context**

## Crash Detail
```
Incident Identifier: dec8e600-e423-41ad-a347-c6d6ca01dd29
CrashReporter Key:   979054C6-C317-44E7-B1C6-C98063046A0A
Hardware Model:      iPhone14,2
Process:         OUR_APP [39698]
Path:            /private/var/containers/Bundle/Application/4503D8CF-F21F-482B-896F-F669047014D6/OUR_APP.app/OUR_APP
Identifier:      com.our.app
Version:         8.7.2 (32763)
Code Type:       arm64
Parent Process:   [1]

Date/Time:       2022-11-11T13:24:22.999Z
Launch Time:     2022-11-11T13:12:46Z
OS Version:      iPhone OS 16.1 (20B82)
Report Version:  104

Exception Type:  SIGSEGV
Exception Codes: SEGV_MAPERR at 0xffffffff
Crashed Thread:  0

Thread 0 Crashed:
0   libobjc.A.dylib                      0x000000019c7c5c08 objc_msgSend + 8
1   CoreFoundation                       0x00000001a34b5ea4 ____NSDictionaryI_new_block_invoke + 180
2   CoreFoundation                       0x00000001a352a1b8 __NSDictionaryI_new + 476
3   Foundation                           0x000000019d91f2dc newJSONObject + 1396
4   Foundation                           0x000000019d91f9f8 newJSONValue + 492
5   Foundation                           0x000000019d8f69f8 -[_NSJSONReader parseData:options:error:] + 1092
6   OUR_APP                              0x0000000105296274 +[OIDIDToken parseJWTSection:] (OIDIDToken.m:118)
7   OUR_APP                              0x0000000105295bac -[OIDIDToken initWithIDTokenString:] (OIDIDToken.m:43)
8   OUR_APP                              0x000000010527fed8 closure #1 (Swift.String?, Swift.String?, Swift.Error?) -> () in closure #1 () -> () in HCAuth.AuthRepoImpl.performAction(additionalParameter: [Swift.String : Swift.String]?, minLifetime: Swift.Double?, forceRefresh: Swift.Bool, freshTokens: (Swift.Result<(accessToken: Swift.String?, idToken: Swift.String?), HCAuthAPI.AuthStateError>) -> ()) -> () (<compiler-generated>:0)
9   OUR_APP                              0x0000000105281f44 partial apply forwarder for closure #1 (Swift.String?, Swift.String?, Swift.Error?) -> () in closure #1 () -> () in HCAuth.AuthRepoImpl.performAction(additionalParameter: [Swift.String : Swift.String]?, minLifetime: Swift.Double?, forceRefresh: Swift.Bool, freshTokens: (Swift.Result<(accessToken: Swift.String?, idToken: Swift.String?), HCAuthAPI.AuthStateError>) -> ()) -> () (<compiler-generated>:0)
10  OUR_APP                              0x000000010528067c reabstraction thunk helper from @escaping @callee_guaranteed (@guaranteed Swift.String?, @guaranteed Swift.String?, @guaranteed Swift.Error?) -> () to @escaping @callee_unowned @convention(block) (@unowned __C.NSString?, @unowned __C.NSString?, @unowned __C.NSError?) -> () (<compiler-generated>:0)
11  OUR_APP                              0x000000010528d7c4 __87-[OIDAuthState performActionWithFreshTokens:additionalRefreshParameters:dispatchQueue:]_block_invoke (OIDAuthState.m:478)
12  libdispatch.dylib                    0x00000001aaa804b4 _dispatch_call_block_and_release + 28
13  libdispatch.dylib                    0x00000001aaa81fdc _dispatch_client_callout + 16
14  libdispatch.dylib                    0x00000001aaa907f4 _dispatch_main_queue_drain + 924
15  libdispatch.dylib                    0x00000001aaa90444 _dispatch_main_queue_callback_4CF + 40
16  CoreFoundation                       0x00000001a35426f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
17  CoreFoundation                       0x00000001a3524058 __CFRunLoopRun + 2032
18  CoreFoundation                       0x00000001a3528ed4 CFRunLoopRunSpecific + 608
19  GraphicsServices                     0x00000001dc82a368 GSEventRunModal + 160
20  UIKitCore                            0x00000001a5a073d0 -[UIApplication _run] + 884
21  UIKitCore                            0x00000001a5a07034 UIApplicationMain + 336
22  OUR_APP                              0x00000001046fc4a0 main (main.m:19)
23  ???                                  0x00000001c1b90960 0x0 + 0
```

**Comment by mdmathias** [comment] 2023-05-18 19:52
I'm not able to reproduce this issue running the [example app](https://github.com/openid/AppAuth-iOS/tree/master/Examples/Example-iOS_ObjC). Please follow up with reproduction steps to help with the debugging. Otherwise, I think the suitable thing to do is close this as not reproducible.

**Comment by mdmathias** [comment] 2023-07-07 16:21
Closing due to a lack of activity.

**Closed** 2023-07-07 16:21 UTC
Labels: bug, triage
