### ISSUE TITLE
UIKit for Mac (Catalyst) support

### ISSUE THREAD

**Issue by jeroenleenarts** [openid/AppAuth-iOS#408] opened 2019-06-21 14:02 UTC
**Are you filing an issue about iOS 12?**
No

**Is your feature request related to a problem? Please describe.**
When compiling against UIKit for Mac (Catalyst, Xcode 11) the build fails with a linker error:

```
Undefined symbols for architecture x86_64:
  _OBJC_CLASS_$_SFAuthenticationSession, referenced from:
      objc-class-ref in OIDExternalUserAgentIOS.o
ld: symbol(s) not found for architecture x86_64
```

**Describe the solution you would like**
Full support for UIKit for Mac.

**Describe alternatives you have considered**
Unsure about possibilities here.

**Additional context**
.

**Comment by jeroenleenarts** [comment] 2019-06-21 14:06
Most likely it is a matter for working around the fact that SFAuthenticationSession is unavailable on UIKit for Mac.

`ASWebAuthenticationSession` is supported. So I hope/expect it is a matter of conditional compilation specific for UIKit for Mac. No other symbols used in AppAuth-iOS seem to be unsupported on UIKit for Mac.

**Comment by WilliamDenniss** [comment] 2019-06-28 03:49
I suspect we'll need a UIKit for Mac specific `OIDExternalUserAgent` implementation. Should be pretty straight forward. May need a separate target as well.

**Comment by below** [comment] 2019-07-01 09:51
While I have not added my own ClientID, I did compile and run master on macOS Catalina. Am I missing steps to reproduce the issue?

**Comment by jeroenleenarts** [comment] 2019-07-02 06:32
@below did you enable UIKIT for Mac?

**Comment by jeroenleenarts** [comment] 2019-07-02 12:34
With these steps I run into the mentioned compile error:

- clone repo
- cd into checkout location and example project `Example_Objc`
- run pod install 
- open `xcworkspace` with xcode beta
- enable mac target on target `Example_Objc`
- Select a valid Team for signing
- build

**Comment by below** [comment] 2019-07-02 12:37
> @below did you enable UIKIT for Mac?

No, how would I do that other than selecting the Mac Target for Example_Objc?

**Comment by jeroenleenarts** [comment] 2019-07-02 12:47
Xcode 11 Beta 2. Ars has a nice overview: https://arstechnica.com/gadgets/2019/07/catalyst-deep-dive-the-future-of-mac-software-according-to-apple-and-devs/

Also, this allows compiling, the example with UIKitForMac:
```
diff --git a/Source/iOS/OIDExternalUserAgentIOS.m b/Source/iOS/OIDExternalUserAgentIOS.m
index 6303d6d..593da11 100644
--- a/Source/iOS/OIDExternalUserAgentIOS.m
+++ b/Source/iOS/OIDExternalUserAgentIOS.m
@@ -38,7 +38,9 @@ NS_ASSUME_NONNULL_BEGIN
 #pragma clang diagnostic push
 #pragma clang diagnostic ignored "-Wpartial-availability"
   __weak SFSafariViewController *_safariVC;
+#if !TARGET_OS_UIKITFORMAC
   SFAuthenticationSession *_authenticationVC;
+#endif
   ASWebAuthenticationSession *_webAuthenticationVC;
 #pragma clang diagnostic pop
 }
@@ -69,7 +71,9 @@ NS_ASSUME_NONNULL_BEGIN
   NSURL *requestURL = [request externalUserAgentRequestURL];
 
   // iOS 12 and later, use ASWebAuthenticationSession
+#if !TARGET_OS_UIKITFORMAC
   if (@available(iOS 12.0, *)) {
+#endif
     // ASWebAuthenticationSession doesn't work with guided access (rdar://40809553)
     if (!UIAccessibilityIsGuidedAccessEnabled()) {
       __weak OIDExternalUserAgentIOS *weakSelf = self;
@@ -97,6 +101,8 @@ NS_ASSUME_NONNULL_BEGIN
       _webAuthenticationVC = authenticationVC;
       openedUserAgent = [authenticationVC start];
     }
+#if !TARGET_OS_UIKITFORMAC
+
   }
   // iOS 11, use SFAuthenticationSession
   if (@available(iOS 11.0, *)) {
@@ -143,6 +149,7 @@ NS_ASSUME_NONNULL_BEGIN
   if (!openedUserAgent){
     openedUserAgent = [[UIApplication sharedApplication] openURL:requestURL];
   }
+#endif
 
   if (!openedUserAgent) {
     [self cleanUp];
@@ -164,7 +171,9 @@ NS_ASSUME_NONNULL_BEGIN
 #pragma clang diagnostic push
 #pragma clang diagnostic ignored "-Wpartial-availability"
   SFSafariViewController *safariVC = _safariVC;
+#if !TARGET_OS_UIKITFORMAC
   SFAuthenticationSession *authenticationVC = _authenticationVC;
+#endif
   ASWebAuthenticationSession *webAuthenticationVC = _webAuthenticationVC;
 #pragma clang diagnostic pop
   
@@ -174,10 +183,12 @@ NS_ASSUME_NONNULL_BEGIN
     // dismiss the ASWebAuthenticationSession
     [webAuthenticationVC cancel];
     if (completion) completion();
+#if !TARGET_OS_UIKITFORMAC
   } else if (authenticationVC) {
     // dismiss the SFAuthenticationSession
     [authenticationVC cancel];
     if (completion) completion();
+#endif
   } else if (safariVC) {
     // dismiss the SFSafariViewController
     [safariVC dismissViewControllerAnimated:YES completion:completion];
@@ -190,7 +201,9 @@ NS_ASSUME_NONNULL_BEGIN
   // The weak references to |_safariVC| and |_session| are set to nil to avoid accidentally using
   // them while not in an authorization flow.
   _safariVC = nil;
+#if !TARGET_OS_UIKITFORMAC
   _authenticationVC = nil;
+#endif
   _session = nil;
   _externalUserAgentFlowInProgress = NO;
 }
```
App starts, but does not work at all yet.

**Comment by jeroenleenarts** [comment] 2019-07-02 12:51
> > @below did you enable UIKIT for Mac?
> 
> No, how would I do that other than selecting the Mac Target for Example_Objc?

![image](https://user-images.githubusercontent.com/39677/60514027-e4fa7900-9cd8-11e9-9ab7-b5815112c22e.png)

**Comment by below** [comment] 2019-07-02 12:53
Now I understand!

**Comment by girishw** [comment] 2019-09-05 05:48
Is there a fix for this coming? Any workarounds in the meantime?

**Comment by kingofkings00** [comment] 2019-09-05 07:29
some gift cards so i can buy what yall broke and stole and i should complain no more and agree whit all your therms! asus 25000nok broken and overheated when someone whas hacking it a day so i took the battery and trowhed it in the street,i have a ipad gen 3 that is 40 codes on,but it work,and a gen 6 too 4500nok that i trowh out in the street in pissed off phsycones,2-3 samsung 5 and 6,a samsung a something work phone,1500nok for repair of harddrive because of hacked tv??😂3months without 12600x3 months,and 4500nok that i gave for my slow shit mac air,i like the pad and iphone,had them since gen1,but learning iox and strings and reding codes etc,i wanna make a retail shop like wish feks,but it have been stolen 6-10 times on amazon and shopify,and my apple id,facebook,what tha fuck?some one else than me need a chill pill and a hit of weed!everygoverment overseas site i go trough it come up millions and millions,and you have fucked my pensjon into stocks,hacked over 94 banks with my personnumber,you can fill a work applycation from alittle head forward this started,and then give me instructions on what to say,sign,and not too say! tired off waking upp and it is always something that is change,or someone talking shit,im not listening att do that do that,we give you free money,all bullshit,and always your not "administrator"???i give a fuck about security and passwords,they all should just bee 1234!!!!! i have a plan,always have!but not this internett shit! so its up too yaall worker gruop,isent i a nice gentlemen that fucking agree too make a deal att all????i hate the system just as yal doo,it isent working right,and call me whatever you like,couldent care less,but im not getting mail,because yaall made digipost fore me,and companies,and fake foreign social security number and have my pass and cards,i have many letters from banks that im involved in whitelaundring,and i cant buy a fucking shit on internett cause you stole all my banks,so i have baby visa whitouht ccv code,so shuta fuck upp and say i musy pay there and use my card there!nevere gonna happen,i have inncjurinse up too 1mill nok trough help id forsikring norge,but i hate courts,police dont like me and i dont like them,but it is no proplem too goo too the police station and make a formal charge,so the lawyer can fix it all,an what as i read i can get alot out off this if i want,and fuck with hell of alot people!!!so out of respect of the nice car youtube guy,please ask someone too tapp the keybord and make some magic,yaall have used "me" so much that you are gettinh yourself caught if im not participating,so hack some magic cards ore some express payment too my norwegian baby account!!!my 8months patience run out today,have a good day!stephan

Sendt fra min iPhone

**Comment by GreenEyeDev2** [comment] 2019-10-02 01:11
Ran into the same issue as well. Is there a patch/workaround currently?

**Comment by neobeppe** [comment] 2019-10-09 13:49
Any news? Catalyst is out of beta

**Comment by dhemku** [comment] 2019-10-14 12:07
Undefined symbols for architecture x86_64:
  "___isPlatformVersionAtLeast", referenced from:
      -[OIDURLQueryComponent initWithURL:] in GoogleSignInDependencies(OIDURLQueryComponent_11dd7a044c46d45a74ebdeeae914b2e4.o)
      -[OIDURLQueryComponent URLEncodedParameters] in GoogleSignInDependencies(OIDURLQueryComponent_11dd7a044c46d45a74ebdeeae914b2e4.o)
      -[OIDExternalUserAgentIOS presentExternalUserAgentRequest:session:] in GoogleSignInDependencies(OIDExternalUserAgentIOS_eda7e1024fb5b0fab30611ed72826e65.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)





I am implementing Google Sign In with Firebase (without Pod),
Any one Help me ? with the help of below link

https://github.com/react-native-community/react-native-google-signin/blob/HEAD/docs/ios-guide.md

**Comment by Praxiades** [comment] 2019-10-24 01:26
The core of the issue is that SFAuthenticationSession is deprecated and was replaced by ASWebAuthenticationSession in iOS 12, for iOS. As Catalyst supports only non-deprecated APIs in iOS 13, SFAuthenticationSession is not supported by Catalyst.

**Comment by girishw** [comment] 2019-10-24 23:56
AppAuth is used by GoogleSign & Firebase authentication, so I'm guessing a lot of people are running into this. Any updates?

**Comment by julienbodet** [comment] 2019-10-28 15:28
Pull request #455 is adding support for this. If anyone here is interested to test it and report any issues encountered, I would appreciate!

**Comment by WilliamDenniss** [comment] 2019-11-21 18:49
Support for Mac Catalyst has been merged into HEAD.

**Closed by WilliamDenniss** 2019-11-21 18:49 UTC
Labels: enhancement, in-scope
