### ISSUE TITLE
Warning: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior

### ISSUE THREAD

**Issue by gloryluu** [openid/AppAuth-iOS#243] opened 2018-05-22 02:38 UTC
Warning: /Volumes/DATA/Projects/the_project_name/project_name/Pods/AppAuth/Source/iOS/OIDAuthorizationUICoordinatorIOS.m:98:7: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior

This happens on cocoa pod current version (0.91.0). Please update the cocoa pod

**Comment by StevenEWright** [comment] 2018-05-22 03:15
Duplicate of #202, which already has a PR #230. I synced with @WilliamDenniss today on this to get it merged. He's on vacation, and will do it soon. The warning can be safely ignored in the meantime.

**Closed by StevenEWright** 2018-05-22 03:15 UTC
Labels: duplicate
