### ISSUE TITLE
IPHONEOS_DEPLOYMENT_TARGET is set to 8.0 but range is 9.0 15.2.99

### ISSUE THREAD

**Issue by BrunoCerberus** [openid/AppAuth-iOS#686] opened 2022-02-25 18:07 UTC
Got these two warnings, I think that is missing some configuration on yours `podfiles` like:

```swift
post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
  end
 end
end
```

<img width="590" alt="Screen Shot 2022-02-25 at 15 05 06" src="https://user-images.githubusercontent.com/10541956/155765455-a51b444d-bdaf-4973-9943-e1e24201cdcc.png">

<img width="592" alt="Screen Shot 2022-02-25 at 15 05 16" src="https://user-images.githubusercontent.com/10541956/155765460-301dc715-a0f5-471f-b687-f1b534611bf0.png">

**Comment by petea** [comment] 2022-03-16 16:44
Duplicate of #601

**Closed by petea** 2022-03-16 16:44 UTC
Labels: duplicate

**Comment by ultimaweapon** [comment] 2022-05-26 23:20
I still having this problem with 1.5.0 using CocoaPods. From what I see #690 is fixing only for SPM.
