### ISSUE TITLE
How to disable SSO

### ISSUE THREAD

**Issue by sandronoel** [openid/AppAuth-iOS#240] opened 2018-05-14 18:20 UTC
how would I go about disabling SSO ? it's causing problems.

**Comment by StevenEWright** [comment] 2018-05-14 19:05
Could you clarify what you’re trying to disable?

**Comment by StevenEWright** [comment] 2018-05-14 19:28
Closing as duplicate of #209 please feel free to reply if you don’t feel this is accurate.

**Closed by StevenEWright** 2018-05-14 19:28 UTC
Labels: duplicate
