### ISSUE TITLE
OIDAuthState.authState not getting the callback with either authState nor error

### ISSUE THREAD

**Issue by arvinthmani** [openid/AppAuth-iOS#683] opened 2022-02-08 14:25 UTC
I am not getting callback from  OIDAuthState.authState after successful authentication. 
Not getting authState object or error as response. Callback is not getting triggered by OIDAuthState.
I am facing this issue suddenly for the past few days. 
No error logs found in server side also.

Is there any way to fix this issue.
Can anybody help me on this.

AppAuth Lib version: 1.4.0
iOS version: iOS 11.0+

Thanks in advance.

@WilliamDenniss

**Comment by mortenkleveland** [comment] 2022-03-17 12:28
Hi @arvinthmani, did you solve this problem?
It started to happen here recently, too. No callback or error is returned.

**Comment by petea** [comment] 2022-03-17 15:56
Can you provide more details of your configuration here, IDP being used, etc?

**Comment by caylab** [comment] 2022-03-18 10:56
As of yesterday, we experience a related issue in our Flutter app, which uses the [flutter_appauth](https://pub.dev/packages/flutter_appauth) package, which is a bridge for this SDK here. The phenomenon may exist a few day longer than we experience it, but it cannot have existed erlier than 2022-03-07 as the authentication worked fine during tests we conducted in past week.

In our case, the initial authentication process happens via Browser/Webkit. After a successful authentication, the browser window closes, but the app does not receive a response, hence nothing happens, neither an exception is thrown, nor does the code continue.

However, this phoenomenon has the following limitations:
* only iOS devices (and emulators) are affected (Android devices and emulators are unaffected)
* all builds of our app are affected, even those which are months old
* return URL has the following impact:
  * `com.example.app://foobar` - app receives no answer and is stuck
  * `com.example.app://` - app receives an answer and code continue

After intensive review and testing, we concluded that it cannot be caused by our app (as all builds are affected), nor can it be our backend code, as rolling back to old version (also using the artifacts from when they were created back then) does not solve the problem.

Hence, we concluded that it can only be related to either this SDK here or the hosting environment our backend is running in, or some iOS directive which somehow came into effect recently and affects several iOS versions.

**Comment by troymccabe** [comment] 2022-03-18 11:28
@caylab You wouldn't happen to be behind Azure Front Door, would you?

**Comment by caylab** [comment] 2022-03-18 12:50
@troymccabe No, we are not using Azure Front Door, as one of my collegues just confirmed.
That being said, we are not familiar with Azure Front Door, so I couldn't tell you anything about it anyway.

**Comment by troymccabe** [comment] 2022-03-18 12:59
Would you be able to share what you're using for your IdP? Social providers or a custom backend? If custom backend, what system is it?

This has been an incredibly annoying one to debug, and I'll come back with more info after more triage.

**Comment by caylab** [comment] 2022-03-18 14:53
I'm not sure, what you mean. 🤔 

If by "social providers", you mean ID via Google, Facebook etc. - no, we're not using those.

We have a custom backend, using OAuth, and the whole backend is Azure hosted.
But I'm not sure what you refer to as the "system".

**Comment by troymccabe** [comment] 2022-03-18 15:35
Ok fun, so...we opened a ticket with Microsoft for this since it does seem like a change on their end that's causing the issue (adding a slash after a path in the `Location` header of a successful authentication).

Once we explained the gravity of it ("All authentication of iOS devices against OAuth IdPs in Azure won't work") that seemed to push things along, so hopefully their product team is able to get to a resolution quickly

**Comment by troymccabe** [comment] 2022-03-18 15:37
@arvinthmani @mortenkleveland Do you guys use Azure as well?

**Comment by mortenkleveland** [comment] 2022-03-18 15:45
Yup! We are using Azure here as well, and the trailing slash (which wasn't there before) in the redirect uri seems to be the problem. 

Thanks for the investigation! Hopefully Microsoft will be able to provide a fix at their end 🤞

**Comment by troymccabe** [comment] 2022-03-18 16:18
@petea Up to you if you want to close this since it does not appear to be related to the lib itself. I would ask that this is left open until we hear back from Microsoft that it's resolved, in case others have the same issue and come here looking for answers 🙏

**Comment by joblolin95** [comment] 2022-03-21 20:07
@troymccabe Is there any open issue for this with Microsoft where this issue can be upvoted or where progress may otherwise be monitored?

**Comment by troymccabe** [comment] 2022-03-21 20:19
Nothing public, unfortunately. Will continue to report back as the issues addressed.

Safe to say you're seeing the same?

**Comment by joblolin95** [comment] 2022-03-21 20:21
Unfortunately, yes.

**Comment by troymccabe** [comment] 2022-03-21 20:24
Yeah, super not great when it's something that we didn't change & has such
a visible impact...Like I said, I'll update (or maybe someone from MS can
jump in, since at least the support personnel are aware of this thread)
when we know more

**Comment by amartens181** [comment] 2022-03-21 21:17
I wonder why Azure is only adding a trailing slash to requests from the iOS AppAuth library. Other clients (including Xamarin iOS ones) are unaffected.

**Comment by mortenkleveland** [comment] 2022-03-21 21:28
@amartens181 We experienced some similar issues with responses from Azure when called from Android, so I am not sure if it has anything to to with the iOS AppAuth library.

On the other side, I'm wondering if the comparison of the response in this library that is too rigid? Perhaps it just should ignore trailing slashes?

**Comment by troymccabe** [comment] 2022-03-21 21:41
:shrug: I personally prefer the explicitness, since both are valid URIs
[1], and if someone wanted to do something weird with
slash-terminated/non-slash-terminated, they could.

Azure resources shouldn't be mucking with responses without being requested
to do so :)

[1]: https://www.rfc-editor.org/rfc/rfc3986#section-3.2

**Comment by troymccabe** [comment] 2022-03-22 17:50
@mortenkleveland @amartens181 @joblolin95 @caylab 

You'll need to raise a ticket with Microsoft. They're doing their RCA, but it sounds like some component of AppService is rewriting values erroneously. I'm not comfortable sharing our ICM, but the message from them was

> They changed something in the front of AppService & it's been adding characters. Sometimes it's a slash, sometimes a space, but they've been seeing it happen. 

They're able to roll out fixes to individual subscriptions from the sounds of it

**Comment by suwatch** [comment] 2022-03-23 23:09
I am from the Azure App Service team.  Apology for the inconvenience, it is a known issue and we are working on mitigating it.   Will update once done.

**Comment by suwatch** [comment] 2022-03-24 16:22
Azure App Service has mitigated the majority of the customers.  The remaining will be mitigated by end of today (2022-03-24).  Please verify and let us know.  We apology for the inconvenience.

**Comment by troymccabe** [comment] 2022-03-24 16:33
Thank you @suwatch, appreciate all the support!

@petea / @arvinthmani This can probably be closed when you get a chance :)

**Closed** 2022-03-24 16:44 UTC
