### ISSUE TITLE
Crashed calling any method after login

### ISSUE THREAD

**Issue by zlstt** [openid/AppAuth-iOS#61] opened 2016-11-22 01:49 UTC
It reports:
Terminating app due to uncaught exception 'Attempted to create a token refresh request from a token response with no refresh token.', reason: 'Attempted to create a token refresh request from a token response with no refresh token.'

**Comment by WilliamDenniss** [comment] 2016-11-22 17:37
Dupe of https://github.com/google/google-api-objectivec-client-for-rest/issues/67

**Closed by WilliamDenniss** 2016-11-22 17:37 UTC

**Comment by WilliamDenniss** [comment] 2016-11-22 18:25
You're not getting a refresh token in your authorization response. Make sure you didn't register your OAuth client at Google as the "Web" type as you will only get a refresh token the first time you authorize a request with a "Web" client.  Valid Google client types for use with AppAuth are "Android", "iOS" and "Other" ("Other" is used for macOS).

#23 allows AppAuth to authorize requests without refresh tokens which will remove this exception, but of course it will only authorize requests until the access token expires (so you should still solve the issue as to why you're not getting a refresh token).
