### ISSUE TITLE
Changing policy

### ISSUE THREAD

**Issue by DanielHJA** [openid/AppAuth-iOS#522] opened 2020-04-08 08:14 UTC
Hello!

An app that I am working on has a bit of a funky flow to it. 

When I click the 'forgot password' link in the app auth window I get an error inside my 'OIDAuthState.authState' block. When this happens, the SFSafariViewController dismisses.

I am wondering if there is any way of keeping the SFSafariController from dismissing and then change the policy so that I am redirected to the correct page.

Thank you!

Regards,

Daniel

**Comment by julienbodet** [comment] 2020-04-30 16:45
Hi, this looks like an issue on your side and not a bug with AppAuth, also I don't get what is the policy you're referring to.

**Comment by julienbodet** [comment] 2020-05-05 14:40
Closing as this does not appear to be a bug in AppAuth. Feel free to open a new issue if you identified a bug in AppAuth.

**Closed by julienbodet** 2020-05-05 14:40 UTC
