### ISSUE TITLE
OIDExternalUserAgentSession.cancel() doesn't cancel and never completes

### ISSUE THREAD

**Issue by steffly** [openid/AppAuth-iOS#771] opened 2023-05-11 23:43 UTC
**Describe the bug**
Please see the repro steps and then more description below.

**To Reproduce**
1. In Swift, make a request using `currentAuthorizationFlow =
                OIDAuthState.authState(byPresenting: authRequest, presenting: viewController, prefersEphemeralSession: true)` with a login_hint specifying an email such as "1@gmail.com".
2. After the auth flow opens, cancel out of it.
3. Make another request, this time with a different email, e.g. "2@gmail.com".

**Expected behavior**
The auth flow should open, this time with the different email prefilled in the login screen.

**Screenshots**
The following shows for a split second:
![image](https://github.com/openid/AppAuth-iOS/assets/110515520/87b93a61-acf8-4925-ac46-2a59549f8b94)
Then it closes. Any subsequent request repeats the same behavior. It's impossible to access auth without restarting the app.

**Environment**
- Device: iPhone 14 emulator
- OS: iOS 16

**Additional context**
This seems to be a race condition with the previous auth flow not having yet cleaned itself up entirely. I believe this to be the case because if you wait before step (3) for long enough, the bug doesn't repro.

To prevent, I tried to wait on the previous flow's cancel method before proceeding with the next auth request.

```
        if let existingFlow = currentAuthorizationFlow {
            existingFlow.cancel(completion: {
                DispatchQueue.main.async {
                    // Make request
                }
                currentAuthorizationFlow = nil
            })
        } else {
            // Make request
        }
        ```
        
However, this did not work because currentAuthorizationFlow's internal `_externalUserAgent` had already been sent to nil, which meant that `dismissExternalUserAgentAnimated` could not be called and `completion` would never trigger.

I was able to fix this bug by making the following change, setting _externalUserAgent to nil at later times:
https://github.com/openid/AppAuth-iOS/commit/f1c72851831ffaf28094e7b090e397f7e49a4a2f

Does this fix make sense? Or is something else going on here?

**Comment by mdmathias** [comment] 2023-05-12 01:56
I'm not able to reproduce this bug with the [GoogleSignIn-iOS sample app](https://github.com/google/GoogleSignIn-iOS/tree/main/Samples/Swift/DaysUntilBirthday). Would you try to reproduce this bug with that sample app? If you can reproduce it, would you share a screen cap of the bug and add more detail to your reproduction steps?

If you cannot reproduce the bug with that sample app, perhaps you could draw some inspiration for how to solve the issue in your code by looking there.

**Comment by mdmathias** [comment] 2023-05-12 02:19
For what it's worth, I also was unable to recreate this issue using [this example app](https://github.com/openid/AppAuth-iOS/tree/1.6.2/Examples/Example-iOS_ObjC) in this repo as well.

**Comment by mdmathias** [comment] 2023-05-12 03:24
Also, if you are using Xcode 14.3, make sure that you bump the version of all of the targets in the example app to be iOS 9.0. See this screenshot as an example. I've created https://github.com/openid/AppAuth-iOS/issues/772 to track bumping those versions in the example apps.
![ios9](https://github.com/openid/AppAuth-iOS/assets/4029922/28045b99-98aa-4177-b349-39dbcadbb5ad)

**Comment by steffly** [comment] 2023-05-12 22:24
Hi @mdmathias , thanks for the responses! I will be looking into trying to reproduce in the examples mentioned. First, though, why the need to target iOS 9.0? We're using constructs from later versions of iOS.

**Comment by mdmathias** [comment] 2023-05-13 01:19
Bumping the targets' minimum version to iOS 9.0 only applies to getting [this example app](https://github.com/openid/AppAuth-iOS/tree/1.6.2/Examples/Example-iOS_ObjC) in AppAuth-iOS to build and run. Xcode 14.3 dropped support for earlier versions of iOS that the example lists as the minimum version of its targets. That will lead to a build error if you try to build and run that example app with Xcode 14.3 directly from the repo. For your purposes, if you're using Xcode 14.3 to build that AppAuth-iOS example app, then the fastest way to resolve that build issue is for you to manually bump the minimum supported version of iOS up to 9.0 yourself.

Let me know what you find in your repro steps.

**Comment by mdmathias** [comment] 2023-05-18 19:53
@steffly Wanted to follow up on this. Are you able to supply reproduction steps, a screen capture so that I can see what the issue looks like, and any stack traces that you think will help? Thanks!

**Comment by steffly** [comment] 2023-05-18 20:00
@mdmathias Hey, thanks for following up!

Situation as it stands: I haven't been able to repro this in the example apps yet. I think we've run afoul of some sort of weird edge case that AppAuth-iOS could probably handle better (it's a shame that the cancel method can sometimes never complete), and we realized it's a timing race condition and found a workaround by adding a 0.5 second delay between a couple steps of our auth handling. That means as it stands we no longer have the bug and we're deprioritizing it--maybe at some point in the future I'll get the chance to dig deeper into it.

Thanks again

**Comment by mdmathias** [comment] 2023-05-18 20:47
Thanks for the update. :) I wonder if looking at the patterns in the sample apps could help show how to avoid this issue and also remove the need for the delay. Otherwise, please do follow up here if you have any reproduction steps to share with something that I can debug myself. In the meantime, I will close this as not reproducible. Please feel free to reopen when you have more to share.

**Closed by mdmathias** 2023-05-18 20:47 UTC
Labels: bug, triage
